host: 0.0.0.0
# User config
author: "Brian Bechtold"
tagline: "Studio"
description: "Welcome to my site, generic desicription text including meta refrences are located here. More coming soon."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "myemail@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
